import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAccess } from "@/lib/session";
import { capacityOn, dealContext, getDeal } from "@/lib/dealsdb";
import { getContract } from "@/lib/contractdb";
import { canSign, ESIGN_CONSENT_TEXT, executionState, renderSignaturePage } from "@/lib/contract";
import { Badge } from "@/components/ui";
import { signContract } from "../../contract-actions";

export const metadata: Metadata = { title: "Agreement" };
const fmt = (d: Date) => new Date(d).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" });
const ROLE: Record<string, string> = { counterparty: "Sponsor", athlete: "Athlete", guardian: "Parent/Legal Guardian" };

export default async function ContractPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; msg?: string }> }) {
  const s = await requireAccess("/dashboard/deals");
  const { id } = await params;
  const q = await searchParams;
  const d = await getDeal(s.userId, id);
  if (!d) notFound();
  const who = await capacityOn(s.userId, d);
  const k = await getContract(id);
  if (!who || !k) notFound();
  const ctx = await dealContext(d);
  const mine = k.signatures.find((x) => x.userId === s.userId);
  const check = canSign({ who, athleteIsMinor: ctx.athleteIsMinor, status: d.status, expired: ctx.expired, voided: !!k.voidedAt, alreadySigned: !!mine });
  const ex = executionState(k.signatures.map((x) => x.role));
  const state = k.voidedAt ? <Badge tone="red">Voided</Badge> : k.executedAt ? <Badge tone="green">Fully executed {fmt(k.executedAt)}</Badge> : <Badge tone="yellow">Awaiting signatures</Badge>;
  const printable = renderSignaturePage(k.sha256, k.signatures.map((x) => ({ role: x.role, typedName: x.typedName, signedAt: x.signedAt.toISOString(), consentVersion: x.consentVersion })));

  return (
    <>
      <h1>Agreement {state}</h1>
      <div className="tag"><Link href={`/dashboard/deals/${id}`} style={{ textDecoration: "underline" }}>← {d.title}</Link> · template {k.templateVersion} · <a href={`/dashboard/deals/${id}/contract/download`} style={{ textDecoration: "underline" }}>Download (.txt)</a></div>
      {q.msg && <p className="ok">{q.msg}</p>}
      {q.error && <p role="alert" className="error">{q.error}</p>}
      <pre className="contract">{k.body}</pre>
      <div className="card" style={{ marginTop: 16 }}>
        <h3>Signatures</h3>
        <p className="muted">Document SHA-256: <code>{k.sha256}</code> — identifies this exact text. Signatures are recorded against it and can&apos;t be altered.</p>
        <table><tbody>
          <tr><td>Sponsor</td><td>{k.signatures.find((x) => x.role === "counterparty") ? <><Badge tone="green">signed</Badge> {k.signatures.find((x) => x.role === "counterparty")!.typedName} · {fmt(k.signatures.find((x) => x.role === "counterparty")!.signedAt)}</> : <Badge tone="gray">not yet</Badge>}</td></tr>
          <tr><td>{ctx.athleteIsMinor ? "Parent/Legal Guardian (for the minor)" : "Athlete"}</td><td>{(() => { const a = k.signatures.find((x) => x.role === "athlete" || x.role === "guardian"); return a ? <><Badge tone="green">signed</Badge> {a.typedName} · {fmt(a.signedAt)} ({ROLE[a.role]})</> : <Badge tone="gray">not yet</Badge>; })()}</td></tr>
        </tbody></table>
        {ex.executed && <p className="ok">Both required parties have signed. Keep a copy: use Download or your browser&apos;s Print → Save as PDF.</p>}
      </div>
      {check.ok && (
        <form action={signContract} className="card" style={{ marginTop: 16, display: "grid", gap: 10, maxWidth: 560 }}>
          <h3>Sign as {ROLE[check.role]}</h3>
          <input type="hidden" name="deal_id" value={id} />
          <label>Type your full name to sign <input type="text" name="typed_name" placeholder="Your full legal name" autoComplete="name" required /></label>
          <label style={{ display: "flex", gap: 8 }}><input type="checkbox" name="consent" /> <span>{ESIGN_CONSENT_TEXT}</span></label>
          <button className="btn" type="submit">Sign agreement</button>
          <p className="muted">Your name must match your account name. We record the time, the document hash and your network details with the signature.</p>
        </form>)}
      {!check.ok && !k.executedAt && !k.voidedAt && !mine && <p className="muted" style={{ marginTop: 16 }}>{check.error}</p>}
      <details style={{ marginTop: 16 }}><summary className="muted">Plain-text signature page</summary><pre className="contract">{printable}</pre></details>
      <p className="disclaimer">This is a template agreement generated by LIN, not legal advice. Rules for minors&apos; contracts and NIL vary by state and association — have counsel review before relying on it.</p>
    </>
  );
}
