import { mfaEnroll } from "./mfa-helper.mjs";
import { chromium } from "playwright";
import { execSync, spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
const B = "http://localhost:3113";
const br = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
let fails = 0, total = 0;
const rec = (ok, k, extra = "") => { total++; if (!ok) fails++; console.log((ok ? "PASS " : "FAIL ") + k.padEnd(76) + (ok ? "" : String(extra).slice(0, 300))); };
const sql = (q) => execSync(`su postgres -c "psql lin -At -q"`, { input: q }).toString().trim();
const dbErr = (q) => { const r = spawnSync("su", ["postgres", "-c", "psql lin -At -q -v ON_ERROR_STOP=1"], { input: q }); return (r.stderr?.toString() ?? "") + (r.status ? " [exit " + r.status + "]" : ""); };
const settle = async (p) => { await p.waitForLoadState("networkidle"); await p.waitForTimeout(1200); await p.waitForLoadState("networkidle"); };
const text = async (p) => (await p.locator("main, .center").first().innerText({ timeout: 2500 }).catch(() => "")).replace(/\s+/g, " ");
async function see(p, re, k) { re = new RegExp(re.source, "i"); let t = ""; for (let i = 0; i < 12; i++) { t = await text(p); if (re.test(t)) return rec(true, k); await p.waitForTimeout(500); } rec(false, k, `got=${t}`); }
const OLD = "longenoughpw1", id = (e) => sql(`select id from users where email='${e}'`);
async function made(f) {
  const ctx = await br.newContext(); const p = await ctx.newPage(); await p.goto(B + "/signup"); await p.waitForSelector("[name=name]");
  await p.fill("[name=name]", f.name); await p.fill("[name=email]", f.email); await p.fill("[name=password]", OLD); await p.check(`[name=role][value=${f.role}]`);
  for (const k of ["sport", "birth_date", "guardian_email"]) if (f[k]) await p.fill(`[name=${k}]`, f[k]);
  await p.click("button[type=submit]"); await settle(p); sql(`update users set email_verified_at=now() where email='${f.email}'`); await p.goto(B + "/dashboard"); await settle(p); return p;
}
const LOG = "/tmp/claude-0/mail.log";
const all = () => readFileSync(LOG, "utf8").split("[mail:dev]").filter((m) => /subject=(New message on a NIL deal|NIL deal update|You have a new NIL offer)/.test(m));
const base = all().length; const mails = () => all().slice(base);


const login = async (p, email, pw = OLD) => { await p.goto(B + "/login"); await p.fill("[name=email]", email); await p.fill("[name=password]", pw); await p.click("button[type=submit]"); await settle(p); };
const bell = async (p) => { await p.goto(B + "/dashboard"); await settle(p); return (await p.locator(".side nav a:has-text('Notifications')").innerText()).replace(/\s+/g, " "); };
const logStart = readFileSync(LOG, "utf8").length;
const mailsTo = (to, subj) => readFileSync(LOG, "utf8").slice(logStart).split("[mail:dev]").filter((m) => m.includes(`to=${to} subject=${subj}`));
const status = async (p, path) => (await p.goto(B + path)).status();
const cron = (path = "") => fetch(B + "/api/cron/daily" + path, { method: "POST", headers: { Authorization: "Bearer test-cron-secret-0123456789abcdef" } }).then((r) => r.json());



sql("truncate users cascade; truncate job_runs");
const sam = await made({ name: "Sam Sponsor", email: "sam@x.com", role: "sponsor" });
const bob = await made({ name: "Bob Booster", email: "bob@x.com", role: "booster" });
const ada = await made({ name: "Ada Adult", email: "ada@x.com", role: "athlete", sport: "Soccer", birth_date: "2000-01-01" });
const jordan = await made({ name: "Jordan Reyes", email: "jordan@x.com", role: "athlete", sport: "Basketball", birth_date: "2010-03-04", guardian_email: "maria@x.com" });
const maria = await made({ name: "Maria Reyes", email: "maria@x.com", role: "parent" });
const eve = await made({ name: "Eve Unrelated", email: "eve@x.com", role: "parent" });
const root = await made({ name: "Root Admin", email: "root@x.com", role: "parent" });
sql("delete from guardian_invites");
sql(`insert into athlete_relationships(athlete_id,member_id,relationship,can_view_academics,can_view_health,guardian_approved) values ('${id("jordan@x.com")}','${id("maria@x.com")}','parent',true,true,true)`);
spawnSync("node", ["scripts/make-admin.mjs", "root@x.com"], { cwd: "/home/user/LIN", env: { ...process.env, DATABASE_URL: "postgres://lin:lin@localhost:5432/lin" } });
await mfaEnroll(root, B);
const U = (e) => id(e);
const feed = async (p, qs = "") => { await p.goto(`${B}/dashboard/feed${qs}`); await settle(p); return text(p); };
const post = async (p, body, files) => { await p.goto(`${B}/dashboard/feed`); await settle(p); await p.locator("textarea[name=body]").fill(body); if (files) await p.locator("input[name=image]").setInputFiles(files);
  await p.locator("main button:text-is('Post')").click(); await settle(p); await p.waitForTimeout(600); };
const PNG = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGP4z8DwHwAFAAH/q842iQAAAABJRU5ErkJggg==", "base64");
const exif = Buffer.from("Exif\0\0GPSLatitude=40.7,GPSLongitude=-74.0,Make=Canon");
const JPG = Buffer.concat([Buffer.from([0xff, 0xd8, 0xff, 0xe0, 0x00, 0x04, 0x4a, 0x46, 0xff, 0xe1, 0x00, exif.length + 2]), exif, Buffer.from([0xff, 0xda, 0x00, 0x02, 0x00, 0xff, 0xd9])]);
const adminForm = async (p, title, vals, button) => { const c = p.locator("main .card", { has: p.locator(`h3:text-is("${title}")`) });
  for (const [k, v] of Object.entries(vals)) await c.locator(`[name="${k}"]`).fill(v); await c.locator(`button:has-text("${button}")`).click(); await settle(p); };
const pid = (like) => sql(`select id from posts where body like '${like}' order by id desc limit 1`);
const view = async (p, path) => { const r = await p.goto(B + path); await settle(p); return r.status(); };

// ============ posting ============
await post(ada, "Big win today, thank you all! Reach me at ada@example.com");
rec(sql("select count(*) from posts where author_id='" + U("ada@x.com") + "'") === "1", "an adult may post (contact details are fine for adults)");
let t = await feed(ada); rec(/Big win today/.test(t), "post appears in the author's feed");
t = await feed(sam, "?tab=discover"); rec(/Big win today/.test(t) && /Ada Adult/.test(t), "strangers find an adult's post under Discover");
t = await feed(sam); rec(!/Big win today/.test(t), "…but not in Following until they follow");
await ada.locator("textarea[name=body]").fill("send nudes"); await ada.locator("main button:text-is('Post')").click(); await settle(ada);
await see(ada, /abusive or inappropriate/, "abusive posts are refused");
rec((await ada.locator("textarea[name=body]").inputValue()) === "send nudes", "the draft stays in the box");
await ada.locator("textarea[name=body]").evaluate((t) => { t.removeAttribute("required"); t.value = "   "; }); await ada.locator("main button:text-is('Post')").click(); await settle(ada);
await see(ada, /Write something first/, "blank posts are refused");
await ada.locator("textarea[name=body]").evaluate((t) => { t.removeAttribute("maxlength"); t.value = "x".repeat(501); }); await ada.locator("main button:text-is('Post')").click(); await settle(ada);
await see(ada, /500 characters/, "over-long posts are refused");
sql(`insert into posts(author_id,body) select '${U("ada@x.com")}','filler '||g from generate_series(1,9) g`);
await post(ada, "one too many");
await see(ada, /posting very quickly/, "posting is rate-limited");
sql(`delete from posts where body like 'filler%' or body='one too many'`);

// ============ pictures ============
await post(ada, "Pic with location data", [{ name: "me.jpg", mimeType: "image/jpeg", buffer: JPG }]);
const withPic = pid("Pic with%");
rec(sql(`select count(*) from post_images where post_id=${withPic}`) === "1", "picture stored");
rec(sql(`select (encode(data,'hex') like '%'||encode('GPSLatitude'::bytea,'hex')||'%')::text || (encode(data,'hex') like '%'||encode('Canon'::bytea,'hex')||'%')::text from post_images where post_id=${withPic}`) === "falsefalse", "GPS and camera data are stripped before storing");
const img = await sam.context().request.get(`${B}/dashboard/feed/image/${withPic}`);
rec(img.status() === 200 && img.headers()["content-type"] === "image/jpeg" && img.headers()["x-content-type-options"] === "nosniff" && /sandbox/.test(img.headers()["content-security-policy"]) && /no-store/.test(img.headers()["cache-control"]), "picture served with nosniff, sandbox and no-store");
rec(!Buffer.from(await img.body()).includes("GPSLatitude"), "served bytes have no location data");
rec((await (await br.newContext()).request.get(`${B}/dashboard/feed/image/${withPic}`)).status() === 401, "signed-out visitors get 401");
await post(ada, "Fake picture", [{ name: "x.png", mimeType: "image/png", buffer: Buffer.from("<html>hi</html>") }]);
await see(ada, /PNG or JPEG/, "a non-image is refused");
await ada.locator("input[name=image]").setInputFiles([{ name: "big.png", mimeType: "image/png", buffer: Buffer.concat([PNG, Buffer.alloc(2 * 1024 * 1024)]) }]); await ada.locator("main button:text-is('Post')").click(); await settle(ada);
await see(ada, /under 2\.0 MB/, "an oversized picture is refused");
await ada.locator("input[name=image]").setInputFiles([{ name: "doc.pdf", mimeType: "application/pdf", buffer: Buffer.from("%PDF-1.4 hi") }]); await ada.locator("main button:text-is('Post')").click(); await settle(ada);
await see(ada, /PNG or JPEG/, "PDFs aren't pictures");
rec(sql("select count(*) from posts where body in ('Fake picture')") === "0", "refused posts were not stored");

// ============ follow, like, comment ============
await view(sam, `/dashboard/feed/u/${U("ada@x.com")}`);
await sam.locator("main button:text-is('Follow')").click(); await settle(sam);
await see(sam, /Following\./, "following an adult is instant");
t = await feed(sam); rec(/Big win today/.test(t), "followed posts appear in Following");
await ada.goto(B + "/dashboard"); await settle(ada);
rec(/Notifications \(1\)/.test(await ada.locator(".side nav a:has-text('Notifications')").innerText()), "the adult is told about a new follower");
await view(sam, `/dashboard/feed/post/${pid("Big win%")}`);
await sam.locator("main button[aria-label='Like']").click(); await sam.waitForTimeout(900);
rec(sql(`select count(*) from post_likes where post_id=${pid("Big win%")}`) === "1", "like is stored");
await sam.reload(); await settle(sam);
rec((await sam.locator("main button[aria-label='Unlike']").count()) === 1, "the heart stays filled after reload");
await sam.locator("main button[aria-label='Unlike']").click(); await sam.waitForTimeout(900);
rec(sql(`select count(*) from post_likes`) === "0", "unlike removes it");
await sam.locator("textarea[name=body]").fill("Congrats! Call me at 555-123-4567"); await sam.locator("main button:text-is('Comment')").click(); await settle(sam); await sam.waitForTimeout(500);
rec(sql("select count(*) from post_comments") === "1", "adults can share contact details in comments on adults' posts");
await sam.locator("textarea[name=body]").fill("you are a bitch"); await sam.locator("main button:text-is('Comment')").click(); await settle(sam);
await see(sam, /abusive or inappropriate/, "abusive comments refused");
await sam.locator("textarea[name=body]").fill("Second comment"); await sam.locator("main button:text-is('Comment')").click(); await settle(sam); await sam.waitForTimeout(500);
rec(sql(`select count(*) from notifications where user_id='${U("ada@x.com")}' and coalesce_key='cmt:${pid("Big win%")}' and read_at is null`) === "1" && sql(`select count from notifications where coalesce_key='cmt:${pid("Big win%")}'`) === "2", "comments fold into one notification");
sql(`insert into post_comments(post_id,author_id,body) select ${pid("Big win%")},'${U("sam@x.com")}','spam '||g from generate_series(1,20) g`);
await sam.locator("textarea[name=body]").fill("rate limited?"); await sam.locator("main button:text-is('Comment')").click(); await settle(sam);
await see(sam, /commenting very quickly/, "comments are rate-limited");
sql(`delete from post_comments where body like 'spam %'`);
await view(sam, `/dashboard/feed/post/${pid("Big win%")}`);
await sam.locator("main form:has(input[name=kind][value=comment]) button:text-is('Delete')").first().click(); await settle(sam);
rec(sql("select count(*) from post_comments where deleted_at is null") === "1", "authors can delete their own comments");
rec((await sam.locator("main summary:has-text('Report')").count()) >= 1 && (await sam.locator("main button:text-is('Delete my post')").count()) === 0, "no 'delete post' on someone else's post");

// ============ minors ============
await post(jordan, "Practice email me at coach@example.com");
await see(jordan, /contact details, links and social handles can't be shared/, "a minor's post can't contain contact details");
await post(jordan, "Game tonight, wish me luck!");
const jp = pid("Game tonight%");
await view(sam, `/dashboard/feed/u/${U("jordan@x.com")}`);
let st = await text(sam);
rec(/Jordan R\./i.test(st) && !/Jordan Reyes/i.test(st) && /Under 18/.test(st) && /Request to follow/.test(st) && !/Game tonight/.test(st), st.slice(0,300) + " — a stranger sees only 'Jordan R.', Under 18 and a request button");
rec((await view(sam, `/dashboard/feed/post/${jp}`)) === 404, "a minor's post is a 404 for non-followers");
t = await feed(sam, "?tab=discover"); rec(!/Game tonight/.test(t), "minors never appear in Discover");
t = await feed(eve, "?tab=discover"); rec(!/Game tonight/.test(t), "…for anyone");
rec((await view(eve, `/dashboard/feed/post/${jp}`)) === 404, "an unlinked parent can't open it");
t = await feed(maria); rec(/Game tonight/.test(t) && /Jordan Reyes/.test(t), "the guardian sees the minor's posts, with the full name, without following");
await view(bob, `/dashboard/feed/u/${U("jordan@x.com")}`);
await bob.locator("main button:text-is('Request to follow')").click(); await settle(bob);
await see(bob, /Boosters and collectives can't follow high-school athletes/, "boosters can't follow minors");
await view(sam, `/dashboard/feed/u/${U("jordan@x.com")}`);
await sam.locator("main button:text-is('Request to follow')").click(); await settle(sam);
await see(sam, /parent\/guardian has to approve/, "following a minor is a request");
rec(sql("select status from follows where follower_id='" + U("sam@x.com") + "' and followee_id='" + U("jordan@x.com") + "'") === "pending", "stored as pending");
rec((await view(sam, `/dashboard/feed/post/${jp}`)) === 404, "a pending request grants nothing");
await maria.goto(B + "/dashboard"); await settle(maria);
rec(/Notifications \(\d+\)/.test(await maria.locator(".side nav a:has-text('Notifications')").innerText()), "the guardian is notified of the request");
await maria.goto(B + "/dashboard/feed/requests"); await settle(maria);
await see(maria, /Sam Sponsor[\s\S]*Jordan Reyes[\s\S]*waiting/i, "the guardian sees the request");
rec((await maria.locator("main button:text-is('Approve')").count()) === 1, "with an Approve button");
rec(/Requests? \(1\)|Follow requests/.test(await feed(maria)), "feed links to requests");
await eve.goto(B + "/dashboard/feed/requests"); await settle(eve);
rec(!/Sam Sponsor/.test(await text(eve)), "an unrelated parent sees no one else's requests");
await maria.goto(B + "/dashboard/feed/requests"); await settle(maria);
await maria.locator("main button:text-is('Approve')").click(); await settle(maria);
rec(sql("select status from follows where followee_id='" + U("jordan@x.com") + "'") === "approved", "approved by the guardian");
t = await feed(sam); rec(/Game tonight/.test(t) && /Jordan R\./.test(t) && !/Jordan Reyes/.test(t), "the approved follower sees the post, with the abbreviated name");
rec((await view(sam, `/dashboard/feed/post/${jp}`)) === 200, "…and can open it");
await sam.locator("textarea[name=body]").fill("Good luck! email me sam@example.com"); await sam.locator("main button:text-is('Comment')").click(); await settle(sam);
await see(sam, /contact details, links and social handles can't be shared/, "comments on a minor's post can't contain contact details");
await sam.locator("textarea[name=body]").fill("Good luck tonight!"); await sam.locator("main button:text-is('Comment')").click(); await settle(sam); await sam.waitForTimeout(500);
rec(sql("select count(*) from post_comments where post_id=" + jp) === "1", "a clean comment goes through");
rec(sql(`select count(*) from notifications where user_id='${U("maria@x.com")}' and coalesce_key='cmt:${jp}'`) === "1" && sql(`select count(*) from notifications where user_id='${U("jordan@x.com")}' and coalesce_key='cmt:${jp}'`) === "1", "the minor and their guardian are both told");
await view(maria, `/dashboard/feed/post/${jp}`); await see(maria, /Sam Sponsor/, "the guardian sees the commenter's real name");
await view(jordan, `/dashboard/feed/post/${jp}`); await see(jordan, /Good luck tonight/, "the athlete sees comments on their own post");
// a minor commenting on an adult's post can't share contact details either
await jordan.locator("textarea[name=body]").fill("call me 555-123-4567"); await jordan.locator("main button:text-is('Comment')").click(); await settle(jordan);
await see(jordan, /can't be shared/, "a minor can't share contact details in comments anywhere");
await maria.goto(B + "/dashboard/feed/requests"); await settle(maria);
await maria.locator("main button:text-is('Remove follower')").click(); await settle(maria);
rec((await view(sam, `/dashboard/feed/post/${jp}`)) === 404 && sql("select count(*) from follows") === "1", "removing a follower cuts off access immediately (Ada's follower remains)");
await post(jordan, "Second post, followers only");
// a minor can block, only a guardian lifts
await view(jordan, `/dashboard/feed/u/${U("sam@x.com")}`);
await jordan.locator("main button:text-is('Block')").click(); await settle(jordan);
await view(jordan, `/dashboard/feed/u/${U("sam@x.com")}`);
await jordan.locator("main button:text-is('Unblock')").click(); await settle(jordan);
await see(jordan, /parent\/guardian lifts blocks/, "a minor can block but not lift it");
rec(sql(`select count(*) from user_blocks where blocker_id='${U("jordan@x.com")}'`) === "1", "the block stays");
sql("delete from user_blocks");

// ============ blocking ============
await view(ada, `/dashboard/feed/u/${U("sam@x.com")}`);
await ada.locator("main button:text-is('Block')").click(); await settle(ada);
rec((await view(sam, `/dashboard/feed/u/${U("ada@x.com")}`)) === 404, "a blocked person gets a 404 on the blocker's profile");
rec((await view(sam, `/dashboard/feed/post/${pid("Big win%")}`)) === 404, "…and on their posts");
t = await feed(sam, "?tab=discover"); rec(!/Big win today/.test(t), "…and Discover hides them");
t = await feed(sam); rec(!/Big win today/.test(t), "…and Following (the follow was removed)");
rec(sql(`select count(*) from follows where follower_id='${U("sam@x.com")}' and followee_id='${U("ada@x.com")}'`) === "0", "blocking removes follows");
rec(!/Sam Sponsor/.test(await (async () => { await view(ada, `/dashboard/feed/post/${pid("Big win%")}`); return text(ada); })()), "the blocker no longer sees the blocked person's comments");
await view(ada, `/dashboard/feed/u/${U("sam@x.com")}`);
rec(/Unblock/.test(await text(ada)), "the blocker can still unblock");
await ada.locator("main button:text-is('Unblock')").click(); await settle(ada);
rec((await view(sam, `/dashboard/feed/u/${U("ada@x.com")}`)) === 200, "unblocking restores visibility");

// ============ reporting & moderation ============
await view(sam, `/dashboard/feed/post/${pid("Big win%")}`);
await sam.locator("main summary:has-text('Report')").first().click();
await sam.locator("main select[name=reason]").first().selectOption("off_platform_contact"); await sam.locator("main textarea[name=note]").first().fill("wants me to call her");
await sam.locator("main button:text-is('Send report')").first().click(); await settle(sam);
await see(sam, /moderator will review/, "a post can be reported");
rec(sql("select count(*) from content_reports where kind='post'") === "1", "stored");
await view(sam, `/dashboard/feed/post/${pid("Big win%")}`);
await sam.locator("main summary:has-text('Report')").first().click(); await sam.locator("main select[name=reason]").first().selectOption("spam"); await sam.locator("main button:text-is('Send report')").first().click(); await settle(sam);
await see(sam, /already reported/, "reporting twice is a no-op");
await view(jordan, `/dashboard/feed/post/${pid("Big win%")}`);
await view(maria, `/dashboard/feed/post/${jp}`);
await maria.goto(`${B}/dashboard/feed/post/${jp}`); await settle(maria);
// urgent report from the guardian on a comment on the minor's post
const mc = sql(`insert into post_comments(post_id,author_id,body) values (${jp},'${U("sam@x.com")}','private comment on jordan') returning id`);
sql(`insert into follows(follower_id,followee_id,status) values ('${U("sam@x.com")}','${U("jordan@x.com")}','approved')`);
await view(maria, `/dashboard/feed/post/${jp}`);
await maria.locator("main li:has-text('private comment') summary:has-text('Report')").click();
await maria.locator("main li:has-text('private comment') select[name=reason]").selectOption("safety_minor"); await maria.locator("main li:has-text('private comment') button:text-is('Send report')").click(); await settle(maria);
rec(sql("select count(*) from content_reports where kind='comment' and reason='safety_minor'") === "1", "a guardian can report a comment on their athlete's post");
rec((await view(sam, `/admin/content-reports`)) === 404 && (await view(ada, `/admin/content-reports/x`)) === 404, "non-admins get 404 on the post report queue");
await root.goto(B + "/admin/content-reports"); await settle(root);
const rows = await root.locator("main tbody tr").allInnerTexts();
rec(rows.length === 2 && /urgent/i.test(rows[0]), "queue lists both, urgent first", rows.join(" | "));
await root.goto(B + "/admin"); await settle(root);
await see(root, /1 urgent post\/comment report/, "overview flags it");
const r1 = sql("select id from content_reports where kind='post'"), r2 = sql("select id from content_reports where kind='comment'");
await root.goto(`${B}/admin/content-reports/${r1}`); await settle(root);
await see(root, /Big win today/, "moderator reads the reported post");
rec(sql("select count(*) from admin_audit where action='view_content_report'") === "1", "reading is audited");
await root.locator("main input[name=reason]").evaluate((i) => i.removeAttribute("minlength"));
await root.locator("main input[name=outcome][value=hide]").check();
await adminForm(root, "Resolve", { reason: "short", password: OLD }, "Resolve"); await see(root, /Give a reason/, "a reason is required");
await root.locator("main input[name=outcome][value=hide]").check();
await adminForm(root, "Resolve", { reason: "Pushes contact outside the app", password: "wrong-password-x" }, "Resolve"); await see(root, /password is incorrect/, "password re-checked");
await root.locator("main input[name=outcome][value=warn]").check();
await adminForm(root, "Resolve", { reason: "Pushes contact outside the app", password: OLD }, "Resolve");
await see(root, /hidden and the author warned/, "hide + warn works");
rec(sql(`select (hidden_at is not null)||':'||body from posts where id=${pid("Big win%")}`).startsWith("true:Big win"), "the post is hidden but its text is kept");
t = await feed(sam, "?tab=discover"); rec(!/Big win today/.test(t), "hidden posts vanish from feeds");
rec((await view(sam, `/dashboard/feed/post/${pid("Big win%")}`)) === 404, "…and can't be opened");
rec((await sam.context().request.get(`${B}/dashboard/feed/image/${withPic}`)).status() === 200, "other posts are unaffected");
rec(sql(`select count(*) from notifications where user_id='${U("sam@x.com")}' and title like 'A moderator reviewed your report%'`) === "1", "the reporter hears the outcome");
rec(sql(`select count(*) from notifications where user_id='${U("ada@x.com")}' and title like 'Something you posted was removed%'`) === "1" && readFileSync(LOG, "utf8").slice(logStart).includes("to=ada@x.com subject=Something you posted on LIN was removed"), "the author is notified and emailed");
await root.goto(`${B}/admin/content-reports/${r2}`); await settle(root);
rec(/under 18/i.test(await text(root)) && /private comment on jordan/.test(await text(root)), "comment report shows the comment and flags the minor");
await root.locator("main input[name=outcome][value=suspend]").check();
await adminForm(root, "Resolve", { reason: "Urgent: unwanted comments on a minor", password: OLD }, "Resolve");
await see(root, /hidden and the author suspended/, "suspend outcome works");
rec(sql(`select (hidden_at is not null) from post_comments where id=${mc}`) === "t" && sql("select (suspended_at is not null) from users where email='sam@x.com'") === "t", "comment hidden and author suspended");
await view(maria, `/dashboard/feed/post/${jp}`);
rec(!/private comment/.test(await text(maria)), "the hidden comment disappears");
sql("update users set suspended_at=null where email='sam@x.com'");
const sam2 = await br.newContext().then((c) => c.newPage()); await login(sam2, "sam@x.com");
// image view by admin audited, only via a report on that post
sql(`insert into content_reports(kind,post_id,reporter_id,reason) values ('post',${withPic},'${U("sam@x.com")}','spam')`);
const r3 = sql(`select id from content_reports where post_id=${withPic}`);
const ai = await root.context().request.get(`${B}/admin/content-reports/${r3}/image`);
rec(ai.status() === 200 && sql("select count(*) from admin_audit where action='view_content_image'") === "1", "admin can view a reported picture, and it's audited");
rec((await root.context().request.get(`${B}/admin/content-reports/${r1}/image`)).status() === 404, "…but not a picture that isn't part of a report");
rec((await sam2.context().request.get(`${B}/admin/content-reports/${r3}/image`)).status() === 404, "non-admins can't");
await root.goto(`${B}/admin/content-reports/${r3}`); await settle(root);
await root.locator("main input[name=outcome][value=dismiss]").check();
await adminForm(root, "Resolve", { reason: "Picture is fine, nothing wrong", password: OLD }, "Resolve"); await see(root, /Report dismissed/, "dismiss works");
rec(sql(`select (hidden_at is null) from posts where id=${withPic}`) === "t", "dismissal leaves the post");
// suspended authors disappear
sql("update users set suspended_at=now() where email='ada@x.com'");
t = await feed(sam2, "?tab=discover"); rec(!/Pic with location/.test(t), "a suspended author's posts disappear");
rec((await view(sam2, `/dashboard/feed/u/${U("ada@x.com")}`)) === 404, "…and their profile");
sql("update users set suspended_at=null where email='ada@x.com'");

// ============ music & status ============
const ID = "4uLU6hMCjMI75M1A2tKUQC";
await view(ada, `/dashboard/feed/u/${U("ada@x.com")}`);
const saveStatus = async (p, st, link, label) => { await p.goto(`${B}/dashboard/feed/u/${id(p === ada ? "ada@x.com" : "jordan@x.com")}`); await settle(p); const c = p.locator("main .card", { has: p.locator("h3:text-is('My status & music')") });
  await c.locator("[name=status_text]").fill(st); await c.locator("[name=music_link]").fill(link); await c.locator("[name=music_label]").fill(label); await c.locator("button:text-is('Save')").click(); await settle(p); };
await saveStatus(ada, "Game day. Locked in.", `https://open.spotify.com.evil.com/track/${ID}`, "x"); await see(ada, /Only Spotify .* and Apple Music/, "look-alike hosts are refused");
await saveStatus(ada, "Game day. Locked in.", "javascript:alert(1)", "x"); await see(ada, /doesn't look like a link|Use the https/, "javascript: links are refused");
await saveStatus(ada, "Game day. Locked in.", `https://open.spotify.com/user/${ID}`, "x"); await see(ada, /isn't a song, album/, "non-music Spotify links are refused");
await saveStatus(ada, "send nudes", `https://open.spotify.com/track/${ID}`, "x"); await see(ada, /abusive or inappropriate/, "status text is screened");
rec(sql("select count(*) from profile_status") === "0", "refused statuses aren't stored");
await saveStatus(ada, "Game day. Locked in.", `https://open.spotify.com/track/${ID}?si=tracker123&evil="><script>`, "Blinding Lights — The Weeknd");
await see(ada, /Status updated/, "a Spotify link is accepted");
rec(sql("select music_provider||':'||music_kind||':'||music_id from profile_status") === `spotify:track:${ID}`, "only the parsed parts are stored (no tracking query string)");
await view(sam2, `/dashboard/feed/u/${U("ada@x.com")}`);
rec(/Game day\. Locked in\./.test(await text(sam2)) && /Blinding Lights/.test(await text(sam2)), "others see the status and song");
rec((await sam2.locator("iframe").count()) === 0, "no third-party iframe loads until someone clicks");
await sam2.locator("main button:has-text('Load Spotify player')").click(); await sam2.waitForTimeout(500);
const fr = sam2.locator("iframe");
rec((await fr.count()) === 1 && (await fr.getAttribute("src")) === `https://open.spotify.com/embed/track/${ID}` && (await fr.getAttribute("referrerpolicy")) === "no-referrer" && (await fr.getAttribute("sandbox")) !== null && !/allow-top-navigation(?!-by-user)/.test((await fr.getAttribute("sandbox")) ?? ""), "after a click the official embed loads, sandboxed, with no referrer", `${await fr.count()} ${await fr.getAttribute("src").catch(() => "")}`);
rec((await sam2.locator("main a:has-text('Open in Spotify')").count()) === 0, "(link replaced by player)");
await post(ada, "Posting with music label");
t = await feed(sam2, "?tab=discover"); rec(/🎵 Blinding Lights/.test(t), "posts show the author's current song");
await saveStatus(ada, "", "https://music.apple.com/us/album/blinding-lights/1499378108?i=1499378112", "Blinding Lights");
await view(sam2, `/dashboard/feed/u/${U("ada@x.com")}`);
await sam2.locator("main button:has-text('Load Apple Music player')").click(); await sam2.waitForTimeout(500);
rec((await sam2.locator("iframe").getAttribute("src")) === "https://embed.music.apple.com/us/album/blinding-lights/1499378108?i=1499378112", "Apple Music embeds work");
sql(`update profile_status set music_id='../../evil' where user_id='${U("ada@x.com")}'`);
await view(sam2, `/dashboard/feed/u/${U("ada@x.com")}`);
rec((await sam2.locator("iframe").count()) === 0 && (await sam2.locator("main button:has-text('Load')").count()) === 0, "a tampered database row never renders a player");
await saveStatus(ada, "", "", ""); rec(sql("select count(*) from profile_status") === "0", "clearing removes the status");
// minor's status visibility
await saveStatus(jordan, "Gym time", `https://open.spotify.com/track/${ID}`, "Hype song");
await view(eve, `/dashboard/feed/u/${U("jordan@x.com")}`);
rec(!/Gym time|Hype song/.test(await text(eve)), "a minor's status and music are hidden from non-followers");
await view(maria, `/dashboard/feed/u/${U("jordan@x.com")}`);
rec(/Gym time/.test(await text(maria)), "…but visible to the guardian");
sql(`delete from follows where follower_id='${U("sam@x.com")}' and followee_id='${U("jordan@x.com")}'`);
await view(sam2, `/dashboard/feed/u/${U("jordan@x.com")}`);
rec(!/Gym time/.test(await text(sam2)), "…and to approved followers only");
sql(`insert into follows(follower_id,followee_id,status) values ('${U("sam@x.com")}','${U("jordan@x.com")}','approved')`);
await view(sam2, `/dashboard/feed/u/${U("jordan@x.com")}`);
rec(/Gym time/.test(await text(sam2)) && /Hype song/.test(await text(sam2)), "…an approved follower sees them");

// ============ deletion ============
sql(`update deals set status='completed'`);
await ada.goto(`${B}/dashboard/settings`); await settle(ada);
const dc = ada.locator("main .card", { has: ada.locator("h3:text-is('Delete account')") });
await dc.locator('[name="password"]').fill(OLD); await dc.locator('[name="confirm"]').fill("DELETE");
await dc.locator('button:has-text("Delete my account")').click(); await new Promise((r) => setTimeout(r, 3000));
const AID = sql("select id from users where deleted_at is not null limit 1");
rec(sql(`select count(*) from posts where author_id='${AID}' and body <> '[deleted]'`) === "0", "a deleted account's posts are blanked");
rec(sql(`select count(*) from post_images where post_id in (select id from posts where author_id='${AID}')`) === "0", "…and their pictures removed");
rec(sql(`select count(*) from follows where follower_id='${AID}' or followee_id='${AID}'`) === "0" && sql(`select count(*) from profile_status where user_id='${AID}'`) === "0", "…follows and status too");
t = await feed(sam2, "?tab=discover"); rec(!/Posting with music label|Pic with location/.test(t), "nothing of theirs remains in feeds");
console.log(fails ? `\n${fails} FAILED (${total} checks)` : `\nALL PASSED (${total} checks)`);
await br.close(); process.exit(fails ? 1 : 0);
